#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sources 41-60. All URLs accessed 2026-09-19; passages verbatim with locators."""
PART3 = [
 {"index":41,"url":"https://arxiv.org/abs/2512.13655","title":"Comparative Analysis of LLM Abliteration Methods: A Cross-Architecture Evaluation (arXiv:2512.13655)",
  "summary":"Four abliteration tools (Heretic, DECCP, ErisForge, FailSpy) x 16 instruction-tuned 7B-14B models; capability preservation on GSM8K (ErisForge -0.28pp, DECCP -0.13pp); cross-architecture abliteration mechanics. Fetched 2026-09-19.",
  "authors":None,"year":2025,
  "supporting_passages":[
   {"quote":"Single-pass methods demonstrated superior capability preservation on the benchmarked subset (avg GSM8K change across three models: ErisForge -0.28 pp; DECCP -0.13 pp)","locator":"arXiv abstract"}]},
 {"index":42,"url":"https://arxiv.org/abs/2607.05842","title":"Beyond Refusal: A Same-Lineage Study of Aligned and Abliterated LLMs (arXiv:2607.05842)",
  "summary":"Same-lineage aligned vs abliterated (Gemma and Qwen) behavioral comparison on software-security workflows; motivationally identical to our within-family design. Fetched 2026-09-19.",
  "authors":None,"year":2026,
  "supporting_passages":[
   {"quote":"we study safety state: whether refusal behavior remains intact (Aligned) or has been refusal-ablated (Abliterated) within same-lineage models ... We compare aligned instruction-tuned models with publicly released refusal-ablated descendants from two model families, Gemma and Qwen.","locator":"arXiv abstract"}]},
 {"index":43,"url":"https://arxiv.org/abs/2602.02132","title":"There Is More to Refusal in LLMs than a Single Direction (Joad et al.)",
  "summary":"Refusal across categories corresponds to geometrically distinct directions, yet steering any produces nearly identical refusal/over-refusal trade-offs (shared one-dimensional control knob); SAE analysis shows a shared refusal-latent core. Fetched 2026-09-19.",
  "authors":None,"year":2026,
  "supporting_passages":[
   {"quote":"across diverse refusal and non-compliance categories, refusal behaviors correspond to geometrically distinct directions in activation space. Yet activation steering along any refusal-related direction produces nearly identical refusal-over-refusal trade-offs, acting as a shared one-dimensional control knob.","locator":"arXiv abstract"}]},
 {"index":44,"url":"https://arxiv.org/abs/2310.01405","title":"Representation Engineering: A Top-Down Approach to AI Transparency (RepE; Zou et al.)",
  "summary":"RepE framework origin (reading/control via representations); difference-in-means concept vectors; fixed example counts without a sample-complexity law. NOTE: correct id is 2310.01405 - verified 2026-09-19. (The iter-1 dep cited 2303.11366, which does not resolve to this paper.)",
  "authors":None,"year":2023,
  "supporting_passages":[]},
 {"index":45,"url":"https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.permutation_test.html","title":"SciPy docs: scipy.stats.permutation_test",
  "summary":"Implementation pin for the LOMO permutation test over models (n_resamples, alternative='two-sided', statistic). Fetched 2026-09-19.",
  "authors":None,"year":None,
  "supporting_passages":[
   {"quote":"scipy.stats.permutation_test(data, statistic, *, permutation_type='independent', vectorized=None, n_resamples=9999, batch=None, alternative='two-sided', axis=0, random_state=None)","locator":"SciPy API reference"}]},
 {"index":46,"url":"https://pingouin-stats.org/generated/pingouin.partial_corr.html","title":"Pingouin docs: pingouin.partial_corr",
  "summary":"Implementation pin for partial Spearman: method='spearman', alternative='two-sided'; reports n, r, p, CI. Fetched 2026-09-19.",
  "authors":None,"year":None,
  "supporting_passages":[
   {"quote":"pingouin.partial_corr(data=None, x=None, y=None, covar=None, x_covar=None, y_covar=None, alternative='two-sided', method='pearson')","locator":"Pingouin API reference"}]},
 {"index":47,"url":"https://scikit-learn.org/stable/modules/generated/sklearn.metrics.cohen_kappa_score.html","title":"sklearn docs: sklearn.metrics.cohen_kappa_score",
  "summary":"Implementation pin for Cohen's kappa (labels, weights, sample_weight). Fetched 2026-09-19.",
  "authors":None,"year":None,
  "supporting_passages":[
   {"quote":"sklearn.metrics.cohen_kappa_score(y1, y2, *, labels=None, weights=None, sample_weight=None)","locator":"sklearn API reference"}]},
 {"index":48,"url":"https://doi.org/10.20982/tqmp.08.1.p023","title":"Hallgren (2012), Computing Inter-Rater Reliability for Observational Data (TQMP)",
  "summary":"Reporting norms for inter-rater reliability (kappa, CIs, base-rate caveats). DOI verified via Crossref 2026-09-19.",
  "authors":["Kevin A. Hallgren"],"year":2012,
  "supporting_passages":[]},
 {"index":49,"url":"https://doi.org/10.2307/2529310","title":"Landis and Koch (1977), The Measurement of Observer Agreement for Categorical Data (Biometrics)",
  "summary":"Kappa interpretation bands (<0 poor ... 0.81-1.00 almost perfect). DOI verified via Crossref 2026-09-19.",
  "authors":["J. Richard Landis","Gary G. Koch"],"year":1977,
  "supporting_passages":[]},
 {"index":50,"url":"https://doi.org/10.1017/CBO9780511802843","title":"Davison and Hinkley (1997), Bootstrap Methods and their Application",
  "summary":"Standard reference for Monte-Carlo permutation p = (1+#extreme)/(1+B) and MC error sqrt(p(1-p)/B). DOI verified via Crossref 2026-09-19.",
  "authors":["Anthony C. Davison","David V. Hinkley"],"year":1997,
  "supporting_passages":[]},
 {"index":51,"url":"https://doi.org/10.1007/978-1-4899-4541-9","title":"Efron and Tibshirani (1993), An Introduction to the Bootstrap",
  "summary":"Bootstrap CIs for small-sample statistics (BCa). DOI verified via Crossref 2026-09-19.",
  "authors":["Bradley Efron","Robert J. Tibshirani"],"year":1993,
  "supporting_passages":[]},
 {"index":52,"url":"https://doi.org/10.21105/joss.01026","title":"Vallat (2018), Pingouin: statistics in Python (Journal of Open Source Software)",
  "summary":"Peer-reviewed citation for the pingouin package. DOI verified via Crossref 2026-09-19.",
  "authors":["Raphael Vallat"],"year":2018,
  "supporting_passages":[]},
 {"index":53,"url":"https://doi.org/10.5351/csam.2015.22.6.665","title":"Kim (2015), ppcor: An R Package for a Fast Calculation to Semi-partial Correlation Coefficients",
  "summary":"Standard reference for the partial-correlation software convention (R cross-check). DOI verified via Crossref 2026-09-19.",
  "authors":["Seongho Kim"],"year":2015,
  "supporting_passages":[]},
 {"index":54,"url":"https://aclanthology.org/2024.naacl-long.301/","title":"XSTest paper (Rottger et al., NAACL 2024, anthology record)",
  "summary":"XSTest paper anthology record: 2024.naacl-long.301, pp. 5377-5400. Fetched 2026-09-19.",
  "authors":["Paul Rottger","Hannah Rose Kirk","Bertie Vidgen","Giuseppe Attanasio","Federico Bianchi","Dirk Hovy"],"year":2024,
  "supporting_passages":[
   {"quote":"doi = \"10.18653/v1/2024.naacl-long.301\", pages = \"5377--5400\"","locator":"readme.md citation block / anthology record"}]},
 {"index":55,"url":"https://github.com/paul-rottger/xstest/tree/main/model_completions","title":"XSTest repo model_completions (reference-score source)",
  "summary":"Repo-shipped completions whose automated labels produce the XSTest reference rows (gpt4, llama2new, llama2orig, mistralguard, mistralinstruct) used as cross-check anchors in the experiment artifacts. Fetched 2026-09-19.",
  "authors":None,"year":2024,
  "supporting_passages":[]},
 {"index":56,"url":"https://arxiv.org/abs/2402.04249","title":"HarmBench paper (Mazeika et al. 2024)",
  "summary":"HarmBench paper: 33 LLMs, 18 attacks; evaluated-model era predates Qwen3/Llama-3.2/Gemma-2 (closest rows: Qwen 7B, Llama-2 7B/13B/70B); ASR values presented in figures only. Fetched 2026-09-19.",
  "authors":["Mantas Mazeika","Long Phan","Xuwang Yin","Andy Zou","Zifan Wang","Norman Mu","Elham Sakhaee","Nathaniel Li","Steven Basart","Bo Li","David Forsyth","Dan Hendrycks"],"year":2024,
  "supporting_passages":[
   {"quote":"Llama 2 7B Llama 2 13B Llama 2 70B Zephyr +R2D2 (Ours) Qwen 7B ... Figure 5. Average attack success","locator":"arXiv:2402.04249, Figure 5 caption (ASR on top models; figure-only values)"}]},
 {"index":57,"url":"https://arxiv.org/abs/2408.17003","title":"Improving Alignment and Robustness with Short Interventions (safety layers; arXiv:2408.17003)",
  "summary":"Safety-critical layers concentrated in contiguous middle layers (iter-1 dep finding, binding; id carried forward; not re-fetched this run).",
  "authors":None,"year":2024,
  "supporting_passages":[]},
 {"index":58,"url":"https://www.lesswrong.com/posts/jGuXSZgv6qfdhMCuJ/refusal-in-llms-is-mediated-by-a-single-direction","title":"LessWrong post: Refusal in LLMs is mediated by a single direction",
  "summary":"Public technical writeup of the Arditi et al. single-direction result (community dissemination); located via search 2026-09-19.",
  "authors":None,"year":2024,
  "supporting_passages":[]},
 {"index":59,"url":"https://proceedings.neurips.cc/paper_files/paper/2024/file/f545448535dfde4f9786555403ab7c49-Paper-Conference.pdf","title":"Refusal in Language Models Is Mediated by a Single Direction (NeurIPS 2024 proceedings version)",
  "summary":"Peer-reviewed proceedings version of Arditi et al. located via search 2026-09-19; directional ablation and activation-addition interventions described.",
  "authors":None,"year":2024,
  "supporting_passages":[
   {"quote":"labeled as directional ablation, reduces refusal rates and elicits unsafe completions. ... To induce refusal, we add the difference-in-means vector r to activations in layer l*","locator":"NeurIPS 2024 proceedings PDF (search snippet)"}]},
 {"index":60,"url":"https://link.springer.com/book/10.1007/0-387-27158-9","title":"Good (2005), Permutation, Parametric and Bootstrap Tests of Hypotheses (Springer)",
  "summary":"Standard reference for permutation-test practice at small n. Chapter records DOI 10.1007/0-387-27158-9_3 verified via Crossref 2026-09-19; book URL cited here.",
  "authors":["Phillip I. Good"],"year":2005,
  "supporting_passages":[]},
]